"""schema initial

Revision ID: 2e89c980794a
Revises: 
Create Date: 2026-07-16 12:01:18.545592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e89c980794a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id_film', sa.Integer(), nullable=False),
    sa.Column('reference_tmdb', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('titre_original', sa.String(length=255), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('affiche', sa.String(length=500), nullable=True),
    sa.Column('duree', sa.SmallInteger(), nullable=True),
    sa.Column('date_sortie', sa.Date(), nullable=True),
    sa.Column('note_moyenne_tmdb', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('date_maj_cache', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_film'),
    sa.UniqueConstraint('reference_tmdb')
    )
    op.create_table('genre',
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_genre'),
    sa.UniqueConstraint('libelle')
    )
    op.create_table('serie',
    sa.Column('id_serie', sa.Integer(), nullable=False),
    sa.Column('reference_tmdb', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('titre_original', sa.String(length=255), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('affiche', sa.String(length=500), nullable=True),
    sa.Column('image_de_fond', sa.String(length=500), nullable=True),
    sa.Column('statut_diffusion', sa.String(length=25), nullable=True),
    sa.Column('date_premiere_diffusion', sa.Date(), nullable=True),
    sa.Column('note_moyenne_tmdb', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('date_maj_cache', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_serie'),
    sa.UniqueConstraint('reference_tmdb')
    )
    op.create_table('utilisateur',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('adresse_mail', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('pseudo', sa.String(length=30), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('date_inscription', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('statut_compte', sa.String(length=20), server_default='actif', nullable=False),
    sa.CheckConstraint("statut_compte IN ('actif','suspendu','supprime')", name='chk_statut_compte'),
    sa.PrimaryKeyConstraint('id_utilisateur'),
    sa.UniqueConstraint('adresse_mail'),
    sa.UniqueConstraint('pseudo')
    )
    op.create_table('appareil',
    sa.Column('id_appareil', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('jeton_notif', sa.String(length=500), nullable=False),
    sa.Column('plateforme', sa.String(length=10), nullable=False),
    sa.Column('date_enregistrement', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_derniere_activite', sa.DateTime(), nullable=True),
    sa.CheckConstraint("plateforme IN ('android','ios','web')", name='chk_plateforme'),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_appareil'),
    sa.UniqueConstraint('jeton_notif')
    )
    op.create_table('categoriser_film',
    sa.Column('id_film', sa.Integer(), nullable=False),
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_film'], ['film.id_film'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_genre'], ['genre.id_genre'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_film', 'id_genre')
    )
    op.create_table('categoriser_serie',
    sa.Column('id_serie', sa.Integer(), nullable=False),
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_genre'], ['genre.id_genre'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_serie'], ['serie.id_serie'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_serie', 'id_genre')
    )
    op.create_table('saison',
    sa.Column('id_saison', sa.Integer(), nullable=False),
    sa.Column('id_serie', sa.Integer(), nullable=False),
    sa.Column('reference_tmdb', sa.Integer(), nullable=False),
    sa.Column('num_saison', sa.SmallInteger(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=True),
    sa.Column('affiche', sa.String(length=500), nullable=True),
    sa.Column('date_diffusion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_serie'], ['serie.id_serie'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_saison'),
    sa.UniqueConstraint('id_serie', 'num_saison', name='uq_saison_numero'),
    sa.UniqueConstraint('reference_tmdb')
    )
    op.create_table('suivre_film',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_film', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=10), nullable=False),
    sa.Column('favori', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("statut IN ('a_voir','vu')", name='chk_statut_film'),
    sa.ForeignKeyConstraint(['id_film'], ['film.id_film'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_utilisateur', 'id_film')
    )
    op.create_table('suivre_serie',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_serie', sa.Integer(), nullable=False),
    sa.Column('statut_suivi', sa.String(length=25), nullable=False),
    sa.Column('favori', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('date_ajout', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("statut_suivi IN ('a_voir','en_cours','terminee','abandonnee','en_pause')", name='chk_statut_suivi'),
    sa.ForeignKeyConstraint(['id_serie'], ['serie.id_serie'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_utilisateur', 'id_serie')
    )
    op.create_table('visionner_film',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_film', sa.Integer(), nullable=False),
    sa.Column('date_visionnage', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_film'], ['film.id_film'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_utilisateur', 'id_film', 'date_visionnage')
    )
    op.create_table('episode',
    sa.Column('id_episode', sa.Integer(), nullable=False),
    sa.Column('id_saison', sa.Integer(), nullable=False),
    sa.Column('reference_tmdb', sa.Integer(), nullable=False),
    sa.Column('num_episode', sa.SmallInteger(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('duree', sa.SmallInteger(), nullable=True),
    sa.Column('date_diffusion', sa.Date(), nullable=True),
    sa.Column('vignette', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_saison'], ['saison.id_saison'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_episode'),
    sa.UniqueConstraint('id_saison', 'num_episode', name='uq_episode_numero'),
    sa.UniqueConstraint('reference_tmdb')
    )
    op.create_index('idx_episode_diffusion', 'episode', ['date_diffusion'], unique=False)
    op.create_table('avis',
    sa.Column('id_avis', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_serie', sa.Integer(), nullable=True),
    sa.Column('id_film', sa.Integer(), nullable=True),
    sa.Column('id_episode', sa.Integer(), nullable=True),
    sa.Column('note', sa.SmallInteger(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(id_serie IS NOT NULL)::int + (id_film IS NOT NULL)::int + (id_episode IS NOT NULL)::int = 1', name='chk_avis_cible'),
    sa.CheckConstraint('note BETWEEN 1 AND 10', name='chk_note'),
    sa.CheckConstraint('note IS NOT NULL OR commentaire IS NOT NULL', name='chk_avis_contenu'),
    sa.ForeignKeyConstraint(['id_episode'], ['episode.id_episode'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_film'], ['film.id_film'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_serie'], ['serie.id_serie'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_avis')
    )
    op.create_table('notification',
    sa.Column('id_notification', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_episode', sa.Integer(), nullable=True),
    sa.Column('id_serie', sa.Integer(), nullable=True),
    sa.Column('id_film', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('contenu', sa.String(length=255), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lue', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("type IN ('nouvel_episode','nouvelle_saison','sortie_film','systeme','rappel')", name='chk_type_notif'),
    sa.CheckConstraint('(id_episode IS NOT NULL)::int + (id_serie IS NOT NULL)::int + (id_film IS NOT NULL)::int <= 1', name='chk_notif_cible'),
    sa.ForeignKeyConstraint(['id_episode'], ['episode.id_episode'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_film'], ['film.id_film'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_serie'], ['serie.id_serie'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_notification')
    )
    op.create_index('idx_notif_user', 'notification', ['id_utilisateur', 'lue'], unique=False)
    op.create_table('visionner_episode',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_episode', sa.Integer(), nullable=False),
    sa.Column('date_visionnage', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('nombre_revisionnage', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['id_episode'], ['episode.id_episode'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_utilisateur', 'id_episode')
    )
    op.create_index('idx_visionner_user', 'visionner_episode', ['id_utilisateur', 'date_visionnage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_visionner_user', table_name='visionner_episode')
    op.drop_table('visionner_episode')
    op.drop_index('idx_notif_user', table_name='notification')
    op.drop_table('notification')
    op.drop_table('avis')
    op.drop_index('idx_episode_diffusion', table_name='episode')
    op.drop_table('episode')
    op.drop_table('visionner_film')
    op.drop_table('suivre_serie')
    op.drop_table('suivre_film')
    op.drop_table('saison')
    op.drop_table('categoriser_serie')
    op.drop_table('categoriser_film')
    op.drop_table('appareil')
    op.drop_table('utilisateur')
    op.drop_table('serie')
    op.drop_table('genre')
    op.drop_table('film')
    # ### end Alembic commands ###
