"""casting des series et des films

Revision ID: 45f08cf1d2b5
Revises: b4c7d1e9f230
Create Date: 2026-09-06 20:30:34.887274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f08cf1d2b5'
down_revision: Union[str, Sequence[str], None] = 'b4c7d1e9f230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acteur',
    sa.Column('id_acteur', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id_acteur')
    )
    op.create_table('casting_film',
    sa.Column('id_film', sa.Integer(), nullable=False),
    sa.Column('id_acteur', sa.Integer(), nullable=False),
    sa.Column('personnage', sa.String(length=255), nullable=True),
    sa.Column('ordre', sa.SmallInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['id_acteur'], ['acteur.id_acteur'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_film'], ['film.id_film'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_film', 'id_acteur')
    )
    op.create_table('casting_serie',
    sa.Column('id_serie', sa.Integer(), nullable=False),
    sa.Column('id_acteur', sa.Integer(), nullable=False),
    sa.Column('personnage', sa.String(length=255), nullable=True),
    sa.Column('ordre', sa.SmallInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['id_acteur'], ['acteur.id_acteur'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_serie'], ['serie.id_serie'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_serie', 'id_acteur')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casting_serie')
    op.drop_table('casting_film')
    op.drop_table('acteur')
    # ### end Alembic commands ###
