"""blocage et signalement (App Store 1.2)

Revision ID: 7baa43454173
Revises: 9517db285a60
Create Date: 2026-09-06 21:25:10.229459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7baa43454173'
down_revision: Union[str, Sequence[str], None] = '9517db285a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocage',
    sa.Column('id_bloqueur', sa.Integer(), nullable=False),
    sa.Column('id_bloque', sa.Integer(), nullable=False),
    sa.Column('date_blocage', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id_bloqueur <> id_bloque', name='chk_pas_auto_blocage'),
    sa.ForeignKeyConstraint(['id_bloque'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_bloqueur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_bloqueur', 'id_bloque')
    )
    op.create_index('idx_blocage_bloque', 'blocage', ['id_bloque'], unique=False)
    op.create_table('signalement',
    sa.Column('id_signalement', sa.Integer(), nullable=False),
    sa.Column('id_signaleur', sa.Integer(), nullable=False),
    sa.Column('id_avis', sa.Integer(), nullable=True),
    sa.Column('id_vise', sa.Integer(), nullable=True),
    sa.Column('motif', sa.String(length=30), nullable=False),
    sa.Column('precision', sa.Text(), nullable=True),
    sa.Column('date_signalement', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('statut', sa.String(length=20), server_default='nouveau', nullable=False),
    sa.CheckConstraint("statut IN ('nouveau','traite','rejete')", name='chk_statut_signalement'),
    sa.CheckConstraint('(id_avis IS NOT NULL)::int + (id_vise IS NOT NULL)::int = 1', name='chk_signalement_cible'),
    sa.ForeignKeyConstraint(['id_avis'], ['avis.id_avis'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_signaleur'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vise'], ['utilisateur.id_utilisateur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_signalement')
    )
    op.create_index('idx_signalement_statut', 'signalement', ['statut'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_signalement_statut', table_name='signalement')
    op.drop_table('signalement')
    op.drop_index('idx_blocage_bloque', table_name='blocage')
    op.drop_table('blocage')
    # ### end Alembic commands ###
