"""horodatages avec fuseau (timestamptz)

Revision ID: 9517db285a60
Revises: 45f08cf1d2b5
Create Date: 2026-09-06 21:13:07.366180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9517db285a60'
down_revision: Union[str, Sequence[str], None] = '45f08cf1d2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abonnement', 'date_abonnement',
               postgresql_using="date_abonnement AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('appareil', 'date_enregistrement',
               postgresql_using="date_enregistrement AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('appareil', 'date_derniere_activite',
               postgresql_using="date_derniere_activite AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('avis', 'date_creation',
               postgresql_using="date_creation AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('avis', 'date_modification',
               postgresql_using="date_modification AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('film', 'date_maj_cache',
               postgresql_using="date_maj_cache AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification', 'date_envoi',
               postgresql_using="date_envoi AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('serie', 'date_maj_cache',
               postgresql_using="date_maj_cache AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('suivre_serie', 'date_ajout',
               postgresql_using="date_ajout AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('utilisateur', 'date_inscription',
               postgresql_using="date_inscription AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('utilisateur', 'date_derniere_connexion',
               postgresql_using="date_derniere_connexion AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('visionner_episode', 'date_visionnage',
               postgresql_using="date_visionnage AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('visionner_film', 'date_visionnage',
               postgresql_using="date_visionnage AT TIME ZONE 'UTC'",
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visionner_film', 'date_visionnage',
               postgresql_using="date_visionnage AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('visionner_episode', 'date_visionnage',
               postgresql_using="date_visionnage AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('utilisateur', 'date_derniere_connexion',
               postgresql_using="date_derniere_connexion AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('utilisateur', 'date_inscription',
               postgresql_using="date_inscription AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('suivre_serie', 'date_ajout',
               postgresql_using="date_ajout AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('serie', 'date_maj_cache',
               postgresql_using="date_maj_cache AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification', 'date_envoi',
               postgresql_using="date_envoi AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('film', 'date_maj_cache',
               postgresql_using="date_maj_cache AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('avis', 'date_modification',
               postgresql_using="date_modification AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('avis', 'date_creation',
               postgresql_using="date_creation AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('appareil', 'date_derniere_activite',
               postgresql_using="date_derniere_activite AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('appareil', 'date_enregistrement',
               postgresql_using="date_enregistrement AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('abonnement', 'date_abonnement',
               postgresql_using="date_abonnement AT TIME ZONE 'UTC'",
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
