"""ajout 'est verifie' pour mail de confirmation

Revision ID: a7a21b8a70e3
Revises: 2e89c980794a
Create Date: 2026-07-20 12:30:09.199751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a21b8a70e3'
down_revision: Union[str, Sequence[str], None] = '2e89c980794a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('est_verifie', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'est_verifie')
    # ### end Alembic commands ###
